services:
  - type: web
    name: atlas-editor-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_CLIENT_ID
        sync: false
      - key: SLACK_CLIENT_SECRET
        sync: false
      - key: SLACK_REDIRECT_URI
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: atlas-editor-db
          property: connectionString
      - key: SESSION_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: CACHE_TTL_SECONDS
        value: 300

  - type: pserv
    name: atlas-editor-db
    env: postgresql
    plan: free

  - type: web
    name: atlas-editor-frontend
    env: static
    buildCommand: cd app && npm install && npm run build
    staticPublishPath: app/dist
    plan: free
    envVars:
      - key: VITE_API_URL
        sync: false
